### ISSUE TITLE
您好，请问paw3395的库和寄存器列表在哪里呢？我没有在项目中找到？

### ISSUE THREAD

**Issue by youziLab** [Ghost-Girls/STM32F042-PMW3360_HID-Mouse#1]
您好，请问paw3395的库和寄存器列表在哪里呢？我没有在项目中找到？

**Comment by nikitalita** [comment]
@lyb36524  https://github.com/ALpotato/zmk/blob/ptdevice-alpotato/app/drivers/sensor/pixart/paw3395/paw3395_priv.c
